//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 05:57:58 PM MSK 
//


package mypackage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CLIENT_CODE"/>
 *         &lt;element ref="{}CLIENT_INFO" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="OperationId" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="20"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="LKU">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="10"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ClientOperation" use="required" type="{}CLIENTOPERATION_Type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clientcode",
    "clientinfo"
})
@XmlRootElement(name = "CLIENT")
public class CLIENT {

    @XmlElement(name = "CLIENT_CODE", required = true)
    protected CLIENTCODE clientcode;
    @XmlElement(name = "CLIENT_INFO")
    protected CLIENTINFO clientinfo;
    @XmlAttribute(name = "OperationId", required = true)
    protected String operationId;
    @XmlAttribute(name = "LKU")
    protected String lku;
    @XmlAttribute(name = "ClientOperation", required = true)
    protected CLIENTOPERATIONType clientOperation;

    /**
     * Gets the value of the clientcode property.
     * 
     * @return
     *     possible object is
     *     {@link CLIENTCODE }
     *     
     */
    public CLIENTCODE getCLIENTCODE() {
        return clientcode;
    }

    /**
     * Sets the value of the clientcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CLIENTCODE }
     *     
     */
    public void setCLIENTCODE(CLIENTCODE value) {
        this.clientcode = value;
    }

    /**
     * Gets the value of the clientinfo property.
     * 
     * @return
     *     possible object is
     *     {@link CLIENTINFO }
     *     
     */
    public CLIENTINFO getCLIENTINFO() {
        return clientinfo;
    }

    /**
     * Sets the value of the clientinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CLIENTINFO }
     *     
     */
    public void setCLIENTINFO(CLIENTINFO value) {
        this.clientinfo = value;
    }

    /**
     * Gets the value of the operationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationId() {
        return operationId;
    }

    /**
     * Sets the value of the operationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationId(String value) {
        this.operationId = value;
    }

    /**
     * Gets the value of the lku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLKU() {
        return lku;
    }

    /**
     * Sets the value of the lku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLKU(String value) {
        this.lku = value;
    }

    /**
     * Gets the value of the clientOperation property.
     * 
     * @return
     *     possible object is
     *     {@link CLIENTOPERATIONType }
     *     
     */
    public CLIENTOPERATIONType getClientOperation() {
        return clientOperation;
    }

    /**
     * Sets the value of the clientOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CLIENTOPERATIONType }
     *     
     */
    public void setClientOperation(CLIENTOPERATIONType value) {
        this.clientOperation = value;
    }

}
