//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 05:57:58 PM MSK 
//


package mypackage;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Данные для идентификации клиента на каждом из рынков
 * 
 * <p>Java class for CLIENT_MARKETS_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CLIENT_MARKETS_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ClientCode" use="required" type="{}CLIENTCODE_Type" />
 *       &lt;attribute name="MarketId" use="required" type="{}MARKETID_Type" />
 *       &lt;attribute name="isIISContract" type="{}YES_NO_Type" default="N" />
 *       &lt;attribute name="isCrossTrades" type="{}CROSSTRADES_TYPE" default="N" />
 *       &lt;attribute name="ClientCodeDescr">
 *         &lt;simpleType>
 *           &lt;restriction base="{}CLIENTCODEDESCR_Type">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="isMainGroupDU" type="{}YES_NO_Type" default="N" />
 *       &lt;attribute name="NumPortfolio">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="20"/>
 *             &lt;minLength value="1"/>
 *             &lt;pattern value="[a-zA-Z0-9]{1,20}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NdsPayer">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;enumeration value="0"/>
 *             &lt;enumeration value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CoCategory">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CLIENT_MARKETS_Type")
@XmlSeeAlso({
    CLIENTMARKETS.class
})
public class CLIENTMARKETSType {

    @XmlAttribute(name = "ClientCode", required = true)
    protected String clientCode;
    @XmlAttribute(name = "MarketId", required = true)
    protected MARKETIDType marketId;
    @XmlAttribute(name = "isIISContract")
    protected YESNOType isIISContract;
    @XmlAttribute(name = "isCrossTrades")
    protected CROSSTRADESTYPE isCrossTrades;
    @XmlAttribute(name = "ClientCodeDescr")
    protected String clientCodeDescr;
    @XmlAttribute(name = "isMainGroupDU")
    protected YESNOType isMainGroupDU;
    @XmlAttribute(name = "NumPortfolio")
    protected String numPortfolio;
    @XmlAttribute(name = "NdsPayer")
    protected BigInteger ndsPayer;
    @XmlAttribute(name = "CoCategory")
    protected BigInteger coCategory;

    /**
     * Gets the value of the clientCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientCode() {
        return clientCode;
    }

    /**
     * Sets the value of the clientCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientCode(String value) {
        this.clientCode = value;
    }

    /**
     * Gets the value of the marketId property.
     * 
     * @return
     *     possible object is
     *     {@link MARKETIDType }
     *     
     */
    public MARKETIDType getMarketId() {
        return marketId;
    }

    /**
     * Sets the value of the marketId property.
     * 
     * @param value
     *     allowed object is
     *     {@link MARKETIDType }
     *     
     */
    public void setMarketId(MARKETIDType value) {
        this.marketId = value;
    }

    /**
     * Gets the value of the isIISContract property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOType }
     *     
     */
    public YESNOType getIsIISContract() {
        if (isIISContract == null) {
            return YESNOType.N;
        } else {
            return isIISContract;
        }
    }

    /**
     * Sets the value of the isIISContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOType }
     *     
     */
    public void setIsIISContract(YESNOType value) {
        this.isIISContract = value;
    }

    /**
     * Gets the value of the isCrossTrades property.
     * 
     * @return
     *     possible object is
     *     {@link CROSSTRADESTYPE }
     *     
     */
    public CROSSTRADESTYPE getIsCrossTrades() {
        if (isCrossTrades == null) {
            return CROSSTRADESTYPE.N;
        } else {
            return isCrossTrades;
        }
    }

    /**
     * Sets the value of the isCrossTrades property.
     * 
     * @param value
     *     allowed object is
     *     {@link CROSSTRADESTYPE }
     *     
     */
    public void setIsCrossTrades(CROSSTRADESTYPE value) {
        this.isCrossTrades = value;
    }

    /**
     * Gets the value of the clientCodeDescr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientCodeDescr() {
        return clientCodeDescr;
    }

    /**
     * Sets the value of the clientCodeDescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientCodeDescr(String value) {
        this.clientCodeDescr = value;
    }

    /**
     * Gets the value of the isMainGroupDU property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOType }
     *     
     */
    public YESNOType getIsMainGroupDU() {
        if (isMainGroupDU == null) {
            return YESNOType.N;
        } else {
            return isMainGroupDU;
        }
    }

    /**
     * Sets the value of the isMainGroupDU property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOType }
     *     
     */
    public void setIsMainGroupDU(YESNOType value) {
        this.isMainGroupDU = value;
    }

    /**
     * Gets the value of the numPortfolio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumPortfolio() {
        return numPortfolio;
    }

    /**
     * Sets the value of the numPortfolio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumPortfolio(String value) {
        this.numPortfolio = value;
    }

    /**
     * Gets the value of the ndsPayer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNdsPayer() {
        return ndsPayer;
    }

    /**
     * Sets the value of the ndsPayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNdsPayer(BigInteger value) {
        this.ndsPayer = value;
    }

    /**
     * Gets the value of the coCategory property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCoCategory() {
        return coCategory;
    }

    /**
     * Sets the value of the coCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCoCategory(BigInteger value) {
        this.coCategory = value;
    }

}
