//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 05:57:58 PM MSK 
//


package mypackage;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CLIENTOPERATION_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CLIENTOPERATION_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;length value="1"/>
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="U"/>
 *     &lt;enumeration value="L"/>
 *     &lt;enumeration value="R"/>
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="D"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CLIENTOPERATION_Type")
@XmlEnum
public enum CLIENTOPERATIONType {


    /**
     * Добавление информации о клиенте
     * 
     */
    A,

    /**
     * Изменение информации о клиенте
     * 
     */
    U,

    /**
     * Добавление привязки кратких кодов на рынках к клиенту
     * 
     */
    L,

    /**
     * Удаление привязки кратких кодов на рынках к клиенту
     * 
     */
    R,

    /**
     * Перемещение привязки кратких кодов на рынках к данному клиенту
     * 
     */
    M,

    /**
     * Удаление информации о клиенте
     * 
     */
    D;

    public String value() {
        return name();
    }

    public static CLIENTOPERATIONType fromValue(String v) {
        return valueOf(v);
    }

}
