//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 05:57:58 PM MSK 
//


package mypackage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Данные для идентификации клиента-брокера
 * 
 * <p>Java class for CLIENT_CODE_MAIN_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CLIENT_CODE_MAIN_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CLIENT_MARKETS_MAIN" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="UniClientCode" type="{}CLIENTCODE_Type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CLIENT_CODE_MAIN_Type", propOrder = {
    "clientmarketsmain"
})
public class CLIENTCODEMAINType {

    @XmlElement(name = "CLIENT_MARKETS_MAIN")
    protected CLIENTMARKETSMAINType clientmarketsmain;
    @XmlAttribute(name = "UniClientCode")
    protected String uniClientCode;

    /**
     * Gets the value of the clientmarketsmain property.
     * 
     * @return
     *     possible object is
     *     {@link CLIENTMARKETSMAINType }
     *     
     */
    public CLIENTMARKETSMAINType getCLIENTMARKETSMAIN() {
        return clientmarketsmain;
    }

    /**
     * Sets the value of the clientmarketsmain property.
     * 
     * @param value
     *     allowed object is
     *     {@link CLIENTMARKETSMAINType }
     *     
     */
    public void setCLIENTMARKETSMAIN(CLIENTMARKETSMAINType value) {
        this.clientmarketsmain = value;
    }

    /**
     * Gets the value of the uniClientCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniClientCode() {
        return uniClientCode;
    }

    /**
     * Sets the value of the uniClientCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniClientCode(String value) {
        this.uniClientCode = value;
    }

}
