//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 05:57:58 PM MSK 
//


package mypackage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CLIENT_CODE_MAIN"/>
 *         &lt;choice>
 *           &lt;element name="PIF">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="INN" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="RegNum" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="20"/>
 *                         &lt;pattern value="[\w-]{1,20}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="NPF_Save">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="INN" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{}INN_LEGAL_Type">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="NPF_Reserv">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="INN" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{}INN_LEGAL_Type">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="NPF_Ustav">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="INN" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{}INN_LEGAL_Type">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="PF">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="INN" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{}INN_LEGAL_Type">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                   &lt;attribute name="InfoIP" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="9"/>
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="HomeMilitary">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="INN" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{}INN_LEGAL_Type">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                   &lt;attribute name="InfoIP" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="9"/>
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="isQualInvestor" type="{}YES_NO_Type" default="N" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clientcodemain",
    "pif",
    "npfSave",
    "npfReserv",
    "npfUstav",
    "pf",
    "homeMilitary"
})
@XmlRootElement(name = "CLIENT_PF")
public class CLIENTPF {

    @XmlElement(name = "CLIENT_CODE_MAIN", required = true)
    protected CLIENTCODEMAINType clientcodemain;
    @XmlElement(name = "PIF")
    protected CLIENTPF.PIF pif;
    @XmlElement(name = "NPF_Save")
    protected CLIENTPF.NPFSave npfSave;
    @XmlElement(name = "NPF_Reserv")
    protected CLIENTPF.NPFReserv npfReserv;
    @XmlElement(name = "NPF_Ustav")
    protected CLIENTPF.NPFUstav npfUstav;
    @XmlElement(name = "PF")
    protected CLIENTPF.PF pf;
    @XmlElement(name = "HomeMilitary")
    protected CLIENTPF.HomeMilitary homeMilitary;
    @XmlAttribute(name = "isQualInvestor")
    protected YESNOType isQualInvestor;

    /**
     * В в этой ноде описана идентификация клиента-управляющего фондом 1-го уровня.
     * 
     * @return
     *     possible object is
     *     {@link CLIENTCODEMAINType }
     *     
     */
    public CLIENTCODEMAINType getCLIENTCODEMAIN() {
        return clientcodemain;
    }

    /**
     * Sets the value of the clientcodemain property.
     * 
     * @param value
     *     allowed object is
     *     {@link CLIENTCODEMAINType }
     *     
     */
    public void setCLIENTCODEMAIN(CLIENTCODEMAINType value) {
        this.clientcodemain = value;
    }

    /**
     * Gets the value of the pif property.
     * 
     * @return
     *     possible object is
     *     {@link CLIENTPF.PIF }
     *     
     */
    public CLIENTPF.PIF getPIF() {
        return pif;
    }

    /**
     * Sets the value of the pif property.
     * 
     * @param value
     *     allowed object is
     *     {@link CLIENTPF.PIF }
     *     
     */
    public void setPIF(CLIENTPF.PIF value) {
        this.pif = value;
    }

    /**
     * Gets the value of the npfSave property.
     * 
     * @return
     *     possible object is
     *     {@link CLIENTPF.NPFSave }
     *     
     */
    public CLIENTPF.NPFSave getNPFSave() {
        return npfSave;
    }

    /**
     * Sets the value of the npfSave property.
     * 
     * @param value
     *     allowed object is
     *     {@link CLIENTPF.NPFSave }
     *     
     */
    public void setNPFSave(CLIENTPF.NPFSave value) {
        this.npfSave = value;
    }

    /**
     * Gets the value of the npfReserv property.
     * 
     * @return
     *     possible object is
     *     {@link CLIENTPF.NPFReserv }
     *     
     */
    public CLIENTPF.NPFReserv getNPFReserv() {
        return npfReserv;
    }

    /**
     * Sets the value of the npfReserv property.
     * 
     * @param value
     *     allowed object is
     *     {@link CLIENTPF.NPFReserv }
     *     
     */
    public void setNPFReserv(CLIENTPF.NPFReserv value) {
        this.npfReserv = value;
    }

    /**
     * Gets the value of the npfUstav property.
     * 
     * @return
     *     possible object is
     *     {@link CLIENTPF.NPFUstav }
     *     
     */
    public CLIENTPF.NPFUstav getNPFUstav() {
        return npfUstav;
    }

    /**
     * Sets the value of the npfUstav property.
     * 
     * @param value
     *     allowed object is
     *     {@link CLIENTPF.NPFUstav }
     *     
     */
    public void setNPFUstav(CLIENTPF.NPFUstav value) {
        this.npfUstav = value;
    }

    /**
     * Gets the value of the pf property.
     * 
     * @return
     *     possible object is
     *     {@link CLIENTPF.PF }
     *     
     */
    public CLIENTPF.PF getPF() {
        return pf;
    }

    /**
     * Sets the value of the pf property.
     * 
     * @param value
     *     allowed object is
     *     {@link CLIENTPF.PF }
     *     
     */
    public void setPF(CLIENTPF.PF value) {
        this.pf = value;
    }

    /**
     * Gets the value of the homeMilitary property.
     * 
     * @return
     *     possible object is
     *     {@link CLIENTPF.HomeMilitary }
     *     
     */
    public CLIENTPF.HomeMilitary getHomeMilitary() {
        return homeMilitary;
    }

    /**
     * Sets the value of the homeMilitary property.
     * 
     * @param value
     *     allowed object is
     *     {@link CLIENTPF.HomeMilitary }
     *     
     */
    public void setHomeMilitary(CLIENTPF.HomeMilitary value) {
        this.homeMilitary = value;
    }

    /**
     * Gets the value of the isQualInvestor property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOType }
     *     
     */
    public YESNOType getIsQualInvestor() {
        if (isQualInvestor == null) {
            return YESNOType.N;
        } else {
            return isQualInvestor;
        }
    }

    /**
     * Sets the value of the isQualInvestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOType }
     *     
     */
    public void setIsQualInvestor(YESNOType value) {
        this.isQualInvestor = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="INN" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{}INN_LEGAL_Type">
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="InfoIP" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;maxLength value="9"/>
     *             &lt;minLength value="1"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class HomeMilitary {

        @XmlAttribute(name = "INN", required = true)
        protected String inn;
        @XmlAttribute(name = "InfoIP", required = true)
        protected String infoIP;

        /**
         * Gets the value of the inn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINN() {
            return inn;
        }

        /**
         * Sets the value of the inn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINN(String value) {
            this.inn = value;
        }

        /**
         * Gets the value of the infoIP property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInfoIP() {
            return infoIP;
        }

        /**
         * Sets the value of the infoIP property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInfoIP(String value) {
            this.infoIP = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="INN" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{}INN_LEGAL_Type">
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class NPFReserv {

        @XmlAttribute(name = "INN", required = true)
        protected String inn;

        /**
         * Gets the value of the inn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINN() {
            return inn;
        }

        /**
         * Sets the value of the inn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINN(String value) {
            this.inn = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="INN" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{}INN_LEGAL_Type">
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class NPFSave {

        @XmlAttribute(name = "INN", required = true)
        protected String inn;

        /**
         * Gets the value of the inn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINN() {
            return inn;
        }

        /**
         * Sets the value of the inn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINN(String value) {
            this.inn = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="INN" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{}INN_LEGAL_Type">
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class NPFUstav {

        @XmlAttribute(name = "INN", required = true)
        protected String inn;

        /**
         * Gets the value of the inn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINN() {
            return inn;
        }

        /**
         * Sets the value of the inn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINN(String value) {
            this.inn = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="INN" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{}INN_LEGAL_Type">
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="InfoIP" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;maxLength value="9"/>
     *             &lt;minLength value="1"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PF {

        @XmlAttribute(name = "INN", required = true)
        protected String inn;
        @XmlAttribute(name = "InfoIP", required = true)
        protected String infoIP;

        /**
         * Gets the value of the inn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINN() {
            return inn;
        }

        /**
         * Sets the value of the inn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINN(String value) {
            this.inn = value;
        }

        /**
         * Gets the value of the infoIP property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInfoIP() {
            return infoIP;
        }

        /**
         * Sets the value of the infoIP property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInfoIP(String value) {
            this.infoIP = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="INN" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="RegNum" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;maxLength value="20"/>
     *             &lt;pattern value="[\w-]{1,20}"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PIF {

        @XmlAttribute(name = "INN")
        protected String inn;
        @XmlAttribute(name = "RegNum", required = true)
        protected String regNum;

        /**
         * Gets the value of the inn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINN() {
            return inn;
        }

        /**
         * Sets the value of the inn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINN(String value) {
            this.inn = value;
        }

        /**
         * Gets the value of the regNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegNum() {
            return regNum;
        }

        /**
         * Sets the value of the regNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegNum(String value) {
            this.regNum = value;
        }

    }

}
