//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 05:57:58 PM MSK 
//


package mypackage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Реквизиты документа в системе электронного документооборота
 * 
 * <p>Java class for DOC_REQUISITES_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DOC_REQUISITES_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DOC_DATE" use="required" type="{}DATE_FORMAT" />
 *       &lt;attribute name="DOC_TIME" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="DOC_NO" use="required" type="{}DOCNO_Type" />
 *       &lt;attribute name="DOC_TYPE_ID" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{}DOCTYPEID_Type">
 *             &lt;pattern value="[E][C][L][I][E][N][T][S]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SENDER_ID" use="required" type="{}UNIFIRMID_Type" />
 *       &lt;attribute name="SENDER_NAME" type="{}FIRMNAME_Type" />
 *       &lt;attribute name="RECEIVER_ID" use="required" type="{}FIRMID_Type" />
 *       &lt;attribute name="REMARKS" type="{}REMARKS_Type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DOC_REQUISITES_Type")
public class DOCREQUISITESType {

    @XmlAttribute(name = "DOC_DATE", required = true)
    protected XMLGregorianCalendar docdate;
    @XmlAttribute(name = "DOC_TIME")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar doctime;
    @XmlAttribute(name = "DOC_NO", required = true)
    protected String docno;
    @XmlAttribute(name = "DOC_TYPE_ID", required = true)
    protected String doctypeid;
    @XmlAttribute(name = "SENDER_ID", required = true)
    protected String senderid;
    @XmlAttribute(name = "SENDER_NAME")
    protected String sendername;
    @XmlAttribute(name = "RECEIVER_ID", required = true)
    protected String receiverid;
    @XmlAttribute(name = "REMARKS")
    protected String remarks;

    /**
     * Gets the value of the docdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDOCDATE() {
        return docdate;
    }

    /**
     * Sets the value of the docdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDOCDATE(XMLGregorianCalendar value) {
        this.docdate = value;
    }

    /**
     * Gets the value of the doctime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDOCTIME() {
        return doctime;
    }

    /**
     * Sets the value of the doctime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDOCTIME(XMLGregorianCalendar value) {
        this.doctime = value;
    }

    /**
     * Gets the value of the docno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCNO() {
        return docno;
    }

    /**
     * Sets the value of the docno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCNO(String value) {
        this.docno = value;
    }

    /**
     * Gets the value of the doctypeid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCTYPEID() {
        return doctypeid;
    }

    /**
     * Sets the value of the doctypeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCTYPEID(String value) {
        this.doctypeid = value;
    }

    /**
     * Gets the value of the senderid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSENDERID() {
        return senderid;
    }

    /**
     * Sets the value of the senderid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSENDERID(String value) {
        this.senderid = value;
    }

    /**
     * Gets the value of the sendername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSENDERNAME() {
        return sendername;
    }

    /**
     * Sets the value of the sendername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSENDERNAME(String value) {
        this.sendername = value;
    }

    /**
     * Gets the value of the receiverid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECEIVERID() {
        return receiverid;
    }

    /**
     * Sets the value of the receiverid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECEIVERID(String value) {
        this.receiverid = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREMARKS() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREMARKS(String value) {
        this.remarks = value;
    }

}
