//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 05:57:58 PM MSK 
//


package mypackage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Данные для идентификации физического лица
 * 
 * <p>Java class for INDIVIDUAL_PERS_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INDIVIDUAL_PERS_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="PASSPORT_RF">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="DocNo" use="required" type="{}PASSPORT_RF_TYPE" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PASSPORT_USSR">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="DocNo" use="required" type="{}PASSPORT_USSR_TYPE" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BIRTH_CERTIFICATE">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="DocNo" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;maxLength value="20"/>
 *                       &lt;minLength value="1"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OTHER_DOC">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="DocNo" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;maxLength value="20"/>
 *                       &lt;minLength value="1"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="isIISContract" type="{}YES_NO_Type" default="N" />
 *       &lt;attribute name="INN" type="{}INN_PHIS_Type" />
 *       &lt;attribute name="FIO">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="200"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INDIVIDUAL_PERS_Type", propOrder = {
    "passportrf",
    "passportussr",
    "birthcertificate",
    "otherdoc"
})
@XmlSeeAlso({
    mypackage.CLIENTSIMPLE.CLIENTINDIVIDUAL.class,
    mypackage.CLIENTDU.CLIENTINDIVIDUAL.class
})
public class INDIVIDUALPERSType {

    @XmlElement(name = "PASSPORT_RF")
    protected INDIVIDUALPERSType.PASSPORTRF passportrf;
    @XmlElement(name = "PASSPORT_USSR")
    protected INDIVIDUALPERSType.PASSPORTUSSR passportussr;
    @XmlElement(name = "BIRTH_CERTIFICATE")
    protected INDIVIDUALPERSType.BIRTHCERTIFICATE birthcertificate;
    @XmlElement(name = "OTHER_DOC")
    protected INDIVIDUALPERSType.OTHERDOC otherdoc;
    @XmlAttribute(name = "isIISContract")
    protected YESNOType isIISContract;
    @XmlAttribute(name = "INN")
    protected String inn;
    @XmlAttribute(name = "FIO")
    protected String fio;

    /**
     * Gets the value of the passportrf property.
     * 
     * @return
     *     possible object is
     *     {@link INDIVIDUALPERSType.PASSPORTRF }
     *     
     */
    public INDIVIDUALPERSType.PASSPORTRF getPASSPORTRF() {
        return passportrf;
    }

    /**
     * Sets the value of the passportrf property.
     * 
     * @param value
     *     allowed object is
     *     {@link INDIVIDUALPERSType.PASSPORTRF }
     *     
     */
    public void setPASSPORTRF(INDIVIDUALPERSType.PASSPORTRF value) {
        this.passportrf = value;
    }

    /**
     * Gets the value of the passportussr property.
     * 
     * @return
     *     possible object is
     *     {@link INDIVIDUALPERSType.PASSPORTUSSR }
     *     
     */
    public INDIVIDUALPERSType.PASSPORTUSSR getPASSPORTUSSR() {
        return passportussr;
    }

    /**
     * Sets the value of the passportussr property.
     * 
     * @param value
     *     allowed object is
     *     {@link INDIVIDUALPERSType.PASSPORTUSSR }
     *     
     */
    public void setPASSPORTUSSR(INDIVIDUALPERSType.PASSPORTUSSR value) {
        this.passportussr = value;
    }

    /**
     * Gets the value of the birthcertificate property.
     * 
     * @return
     *     possible object is
     *     {@link INDIVIDUALPERSType.BIRTHCERTIFICATE }
     *     
     */
    public INDIVIDUALPERSType.BIRTHCERTIFICATE getBIRTHCERTIFICATE() {
        return birthcertificate;
    }

    /**
     * Sets the value of the birthcertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link INDIVIDUALPERSType.BIRTHCERTIFICATE }
     *     
     */
    public void setBIRTHCERTIFICATE(INDIVIDUALPERSType.BIRTHCERTIFICATE value) {
        this.birthcertificate = value;
    }

    /**
     * Gets the value of the otherdoc property.
     * 
     * @return
     *     possible object is
     *     {@link INDIVIDUALPERSType.OTHERDOC }
     *     
     */
    public INDIVIDUALPERSType.OTHERDOC getOTHERDOC() {
        return otherdoc;
    }

    /**
     * Sets the value of the otherdoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link INDIVIDUALPERSType.OTHERDOC }
     *     
     */
    public void setOTHERDOC(INDIVIDUALPERSType.OTHERDOC value) {
        this.otherdoc = value;
    }

    /**
     * Gets the value of the isIISContract property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOType }
     *     
     */
    public YESNOType getIsIISContract() {
        if (isIISContract == null) {
            return YESNOType.N;
        } else {
            return isIISContract;
        }
    }

    /**
     * Sets the value of the isIISContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOType }
     *     
     */
    public void setIsIISContract(YESNOType value) {
        this.isIISContract = value;
    }

    /**
     * Gets the value of the inn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINN() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINN(String value) {
        this.inn = value;
    }

    /**
     * Gets the value of the fio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIO() {
        return fio;
    }

    /**
     * Sets the value of the fio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIO(String value) {
        this.fio = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="DocNo" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;maxLength value="20"/>
     *             &lt;minLength value="1"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class BIRTHCERTIFICATE {

        @XmlAttribute(name = "DocNo", required = true)
        protected String docNo;

        /**
         * Gets the value of the docNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocNo() {
            return docNo;
        }

        /**
         * Sets the value of the docNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocNo(String value) {
            this.docNo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="DocNo" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;maxLength value="20"/>
     *             &lt;minLength value="1"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class OTHERDOC {

        @XmlAttribute(name = "DocNo", required = true)
        protected String docNo;

        /**
         * Gets the value of the docNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocNo() {
            return docNo;
        }

        /**
         * Sets the value of the docNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocNo(String value) {
            this.docNo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="DocNo" use="required" type="{}PASSPORT_RF_TYPE" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PASSPORTRF {

        @XmlAttribute(name = "DocNo", required = true)
        protected String docNo;

        /**
         * Gets the value of the docNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocNo() {
            return docNo;
        }

        /**
         * Sets the value of the docNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocNo(String value) {
            this.docNo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="DocNo" use="required" type="{}PASSPORT_USSR_TYPE" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PASSPORTUSSR {

        @XmlAttribute(name = "DocNo", required = true)
        protected String docNo;

        /**
         * Gets the value of the docNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocNo() {
            return docNo;
        }

        /**
         * Sets the value of the docNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocNo(String value) {
            this.docNo = value;
        }

    }

}
