//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 05:57:58 PM MSK 
//


package mypackage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Данные для идентификации юридического лица ДУ
 * 
 * <p>Java class for LEGAL_PERS_DU_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LEGAL_PERS_DU_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="INN">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="DocNo" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{}INN_LEGAL_Type">
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="KIO">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="DocNo" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{}KIO_TYPE">
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="isInsureLicense" type="{}YES_NO_Type" default="N" />
 *       &lt;attribute name="isCurrencyLicense" type="{}YES_NO_Type" default="N" />
 *       &lt;attribute name="BankLicense" type="{}BANKLICENSE_Type" />
 *       &lt;attribute name="ShortName">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="200"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LEGAL_PERS_DU_Type", propOrder = {
    "inn",
    "kio"
})
public class LEGALPERSDUType {

    @XmlElement(name = "INN")
    protected LEGALPERSDUType.INN inn;
    @XmlElement(name = "KIO")
    protected LEGALPERSDUType.KIO kio;
    @XmlAttribute(name = "isInsureLicense")
    protected YESNOType isInsureLicense;
    @XmlAttribute(name = "isCurrencyLicense")
    protected YESNOType isCurrencyLicense;
    @XmlAttribute(name = "BankLicense")
    protected String bankLicense;
    @XmlAttribute(name = "ShortName")
    protected String shortName;

    /**
     * Gets the value of the inn property.
     * 
     * @return
     *     possible object is
     *     {@link LEGALPERSDUType.INN }
     *     
     */
    public LEGALPERSDUType.INN getINN() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     * 
     * @param value
     *     allowed object is
     *     {@link LEGALPERSDUType.INN }
     *     
     */
    public void setINN(LEGALPERSDUType.INN value) {
        this.inn = value;
    }

    /**
     * Gets the value of the kio property.
     * 
     * @return
     *     possible object is
     *     {@link LEGALPERSDUType.KIO }
     *     
     */
    public LEGALPERSDUType.KIO getKIO() {
        return kio;
    }

    /**
     * Sets the value of the kio property.
     * 
     * @param value
     *     allowed object is
     *     {@link LEGALPERSDUType.KIO }
     *     
     */
    public void setKIO(LEGALPERSDUType.KIO value) {
        this.kio = value;
    }

    /**
     * Gets the value of the isInsureLicense property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOType }
     *     
     */
    public YESNOType getIsInsureLicense() {
        if (isInsureLicense == null) {
            return YESNOType.N;
        } else {
            return isInsureLicense;
        }
    }

    /**
     * Sets the value of the isInsureLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOType }
     *     
     */
    public void setIsInsureLicense(YESNOType value) {
        this.isInsureLicense = value;
    }

    /**
     * Gets the value of the isCurrencyLicense property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOType }
     *     
     */
    public YESNOType getIsCurrencyLicense() {
        if (isCurrencyLicense == null) {
            return YESNOType.N;
        } else {
            return isCurrencyLicense;
        }
    }

    /**
     * Sets the value of the isCurrencyLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOType }
     *     
     */
    public void setIsCurrencyLicense(YESNOType value) {
        this.isCurrencyLicense = value;
    }

    /**
     * Gets the value of the bankLicense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankLicense() {
        return bankLicense;
    }

    /**
     * Sets the value of the bankLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankLicense(String value) {
        this.bankLicense = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="DocNo" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{}INN_LEGAL_Type">
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class INN {

        @XmlAttribute(name = "DocNo", required = true)
        protected String docNo;

        /**
         * Gets the value of the docNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocNo() {
            return docNo;
        }

        /**
         * Sets the value of the docNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocNo(String value) {
            this.docNo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="DocNo" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{}KIO_TYPE">
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class KIO {

        @XmlAttribute(name = "DocNo", required = true)
        protected String docNo;

        /**
         * Gets the value of the docNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocNo() {
            return docNo;
        }

        /**
         * Sets the value of the docNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocNo(String value) {
            this.docNo = value;
        }

    }

}
