//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 05:57:58 PM MSK 
//


package mypackage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Данные для идентификации юридического лица
 * 
 * <p>Java class for LEGAL_PERS_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LEGAL_PERS_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="INN">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="DocNo" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{}INN_LEGAL_Type">
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="KIO">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="DocNo" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{}KIO_TYPE">
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="isSelfFirm" type="{}YES_NO_Type" default="N" />
 *       &lt;attribute name="isInsureLicense" type="{}YES_NO_Type" default="N" />
 *       &lt;attribute name="isCurrencyLicense" type="{}YES_NO_Type" default="N" />
 *       &lt;attribute name="BankLicense" type="{}BANKLICENSE_Type" />
 *       &lt;attribute name="isMainBroker" type="{}YES_NO_Type" default="N" />
 *       &lt;attribute name="isMainSingleDU" type="{}YES_NO_Type" default="N" />
 *       &lt;attribute name="isMainGroupDU" type="{}YES_NO_Type" default="N" />
 *       &lt;attribute name="isMainPF" type="{}YES_NO_Type" default="N" />
 *       &lt;attribute name="ShortName">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="200"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="isMainNotRezDU" type="{}YES_NO_Type" default="N" />
 *       &lt;attribute name="NonresidentTaxCode">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="20"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SwiftCode">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="40"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ClearingUnicode" type="{}UNIFIRMID_Type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LEGAL_PERS_Type", propOrder = {
    "inn",
    "kio"
})
public class LEGALPERSType {

    @XmlElement(name = "INN")
    protected LEGALPERSType.INN inn;
    @XmlElement(name = "KIO")
    protected LEGALPERSType.KIO kio;
    @XmlAttribute(name = "isSelfFirm")
    protected YESNOType isSelfFirm;
    @XmlAttribute(name = "isInsureLicense")
    protected YESNOType isInsureLicense;
    @XmlAttribute(name = "isCurrencyLicense")
    protected YESNOType isCurrencyLicense;
    @XmlAttribute(name = "BankLicense")
    protected String bankLicense;
    @XmlAttribute(name = "isMainBroker")
    protected YESNOType isMainBroker;
    @XmlAttribute(name = "isMainSingleDU")
    protected YESNOType isMainSingleDU;
    @XmlAttribute(name = "isMainGroupDU")
    protected YESNOType isMainGroupDU;
    @XmlAttribute(name = "isMainPF")
    protected YESNOType isMainPF;
    @XmlAttribute(name = "ShortName")
    protected String shortName;
    @XmlAttribute(name = "isMainNotRezDU")
    protected YESNOType isMainNotRezDU;
    @XmlAttribute(name = "NonresidentTaxCode")
    protected String nonresidentTaxCode;
    @XmlAttribute(name = "SwiftCode")
    protected String swiftCode;
    @XmlAttribute(name = "ClearingUnicode")
    protected String clearingUnicode;

    /**
     * Gets the value of the inn property.
     * 
     * @return
     *     possible object is
     *     {@link LEGALPERSType.INN }
     *     
     */
    public LEGALPERSType.INN getINN() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     * 
     * @param value
     *     allowed object is
     *     {@link LEGALPERSType.INN }
     *     
     */
    public void setINN(LEGALPERSType.INN value) {
        this.inn = value;
    }

    /**
     * Gets the value of the kio property.
     * 
     * @return
     *     possible object is
     *     {@link LEGALPERSType.KIO }
     *     
     */
    public LEGALPERSType.KIO getKIO() {
        return kio;
    }

    /**
     * Sets the value of the kio property.
     * 
     * @param value
     *     allowed object is
     *     {@link LEGALPERSType.KIO }
     *     
     */
    public void setKIO(LEGALPERSType.KIO value) {
        this.kio = value;
    }

    /**
     * Gets the value of the isSelfFirm property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOType }
     *     
     */
    public YESNOType getIsSelfFirm() {
        if (isSelfFirm == null) {
            return YESNOType.N;
        } else {
            return isSelfFirm;
        }
    }

    /**
     * Sets the value of the isSelfFirm property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOType }
     *     
     */
    public void setIsSelfFirm(YESNOType value) {
        this.isSelfFirm = value;
    }

    /**
     * Gets the value of the isInsureLicense property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOType }
     *     
     */
    public YESNOType getIsInsureLicense() {
        if (isInsureLicense == null) {
            return YESNOType.N;
        } else {
            return isInsureLicense;
        }
    }

    /**
     * Sets the value of the isInsureLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOType }
     *     
     */
    public void setIsInsureLicense(YESNOType value) {
        this.isInsureLicense = value;
    }

    /**
     * Gets the value of the isCurrencyLicense property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOType }
     *     
     */
    public YESNOType getIsCurrencyLicense() {
        if (isCurrencyLicense == null) {
            return YESNOType.N;
        } else {
            return isCurrencyLicense;
        }
    }

    /**
     * Sets the value of the isCurrencyLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOType }
     *     
     */
    public void setIsCurrencyLicense(YESNOType value) {
        this.isCurrencyLicense = value;
    }

    /**
     * Gets the value of the bankLicense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankLicense() {
        return bankLicense;
    }

    /**
     * Sets the value of the bankLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankLicense(String value) {
        this.bankLicense = value;
    }

    /**
     * Gets the value of the isMainBroker property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOType }
     *     
     */
    public YESNOType getIsMainBroker() {
        if (isMainBroker == null) {
            return YESNOType.N;
        } else {
            return isMainBroker;
        }
    }

    /**
     * Sets the value of the isMainBroker property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOType }
     *     
     */
    public void setIsMainBroker(YESNOType value) {
        this.isMainBroker = value;
    }

    /**
     * Gets the value of the isMainSingleDU property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOType }
     *     
     */
    public YESNOType getIsMainSingleDU() {
        if (isMainSingleDU == null) {
            return YESNOType.N;
        } else {
            return isMainSingleDU;
        }
    }

    /**
     * Sets the value of the isMainSingleDU property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOType }
     *     
     */
    public void setIsMainSingleDU(YESNOType value) {
        this.isMainSingleDU = value;
    }

    /**
     * Gets the value of the isMainGroupDU property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOType }
     *     
     */
    public YESNOType getIsMainGroupDU() {
        if (isMainGroupDU == null) {
            return YESNOType.N;
        } else {
            return isMainGroupDU;
        }
    }

    /**
     * Sets the value of the isMainGroupDU property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOType }
     *     
     */
    public void setIsMainGroupDU(YESNOType value) {
        this.isMainGroupDU = value;
    }

    /**
     * Gets the value of the isMainPF property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOType }
     *     
     */
    public YESNOType getIsMainPF() {
        if (isMainPF == null) {
            return YESNOType.N;
        } else {
            return isMainPF;
        }
    }

    /**
     * Sets the value of the isMainPF property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOType }
     *     
     */
    public void setIsMainPF(YESNOType value) {
        this.isMainPF = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the isMainNotRezDU property.
     * 
     * @return
     *     possible object is
     *     {@link YESNOType }
     *     
     */
    public YESNOType getIsMainNotRezDU() {
        if (isMainNotRezDU == null) {
            return YESNOType.N;
        } else {
            return isMainNotRezDU;
        }
    }

    /**
     * Sets the value of the isMainNotRezDU property.
     * 
     * @param value
     *     allowed object is
     *     {@link YESNOType }
     *     
     */
    public void setIsMainNotRezDU(YESNOType value) {
        this.isMainNotRezDU = value;
    }

    /**
     * Gets the value of the nonresidentTaxCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonresidentTaxCode() {
        return nonresidentTaxCode;
    }

    /**
     * Sets the value of the nonresidentTaxCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonresidentTaxCode(String value) {
        this.nonresidentTaxCode = value;
    }

    /**
     * Gets the value of the swiftCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwiftCode() {
        return swiftCode;
    }

    /**
     * Sets the value of the swiftCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwiftCode(String value) {
        this.swiftCode = value;
    }

    /**
     * Gets the value of the clearingUnicode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClearingUnicode() {
        return clearingUnicode;
    }

    /**
     * Sets the value of the clearingUnicode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClearingUnicode(String value) {
        this.clearingUnicode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="DocNo" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{}INN_LEGAL_Type">
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class INN {

        @XmlAttribute(name = "DocNo", required = true)
        protected String docNo;

        /**
         * Gets the value of the docNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocNo() {
            return docNo;
        }

        /**
         * Sets the value of the docNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocNo(String value) {
            this.docNo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="DocNo" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{}KIO_TYPE">
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class KIO {

        @XmlAttribute(name = "DocNo", required = true)
        protected String docNo;

        /**
         * Gets the value of the docNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocNo() {
            return docNo;
        }

        /**
         * Sets the value of the docNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocNo(String value) {
            this.docNo = value;
        }

    }

}
