//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 05:57:58 PM MSK 
//


package mypackage;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MARKETID_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MARKETID_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;minLength value="2"/>
 *     &lt;maxLength value="4"/>
 *     &lt;enumeration value="CU"/>
 *     &lt;enumeration value="SE"/>
 *     &lt;enumeration value="FO"/>
 *     &lt;enumeration value="PF"/>
 *     &lt;enumeration value="CO"/>
 *     &lt;enumeration value="DE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MARKETID_Type")
@XmlEnum
public enum MARKETIDType {

    CU,
    SE,
    FO,
    PF,
    CO,
    DE;

    public String value() {
        return name();
    }

    public static MARKETIDType fromValue(String v) {
        return valueOf(v);
    }

}
