//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 05:57:58 PM MSK 
//


package mypackage;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mypackage package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CLIENTCODEMAIN_QNAME = new QName("", "CLIENT_CODE_MAIN");
    private final static QName _DOCREQUISITES_QNAME = new QName("", "DOC_REQUISITES");
    private final static QName _REPRESENTATIVEPERS_QNAME = new QName("", "REPRESENTATIVE_PERS");
    private final static QName _CLIENTMARKETSMAIN_QNAME = new QName("", "CLIENT_MARKETS_MAIN");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mypackage
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CLIENTSIMPLE }
     * 
     */
    public CLIENTSIMPLE createCLIENTSIMPLE() {
        return new CLIENTSIMPLE();
    }

    /**
     * Create an instance of {@link CLIENTDU }
     * 
     */
    public CLIENTDU createCLIENTDU() {
        return new CLIENTDU();
    }

    /**
     * Create an instance of {@link CLIENTPF }
     * 
     */
    public CLIENTPF createCLIENTPF() {
        return new CLIENTPF();
    }

    /**
     * Create an instance of {@link INDIVIDUALPERSType }
     * 
     */
    public INDIVIDUALPERSType createINDIVIDUALPERSType() {
        return new INDIVIDUALPERSType();
    }

    /**
     * Create an instance of {@link REPRESENTATIVEPERSType }
     * 
     */
    public REPRESENTATIVEPERSType createREPRESENTATIVEPERSType() {
        return new REPRESENTATIVEPERSType();
    }

    /**
     * Create an instance of {@link LEGALPERSDUType }
     * 
     */
    public LEGALPERSDUType createLEGALPERSDUType() {
        return new LEGALPERSDUType();
    }

    /**
     * Create an instance of {@link LEGALPERSType }
     * 
     */
    public LEGALPERSType createLEGALPERSType() {
        return new LEGALPERSType();
    }

    /**
     * Create an instance of {@link CLIENTCODEMAINType }
     * 
     */
    public CLIENTCODEMAINType createCLIENTCODEMAINType() {
        return new CLIENTCODEMAINType();
    }

    /**
     * Create an instance of {@link DOCREQUISITESType }
     * 
     */
    public DOCREQUISITESType createDOCREQUISITESType() {
        return new DOCREQUISITESType();
    }

    /**
     * Create an instance of {@link CLIENTSIMPLE.CLIENTINDIVIDUAL }
     * 
     */
    public CLIENTSIMPLE.CLIENTINDIVIDUAL createCLIENTSIMPLECLIENTINDIVIDUAL() {
        return new CLIENTSIMPLE.CLIENTINDIVIDUAL();
    }

    /**
     * Create an instance of {@link CLIENTMARKETSMAINType }
     * 
     */
    public CLIENTMARKETSMAINType createCLIENTMARKETSMAINType() {
        return new CLIENTMARKETSMAINType();
    }

    /**
     * Create an instance of {@link CLIENT }
     * 
     */
    public CLIENT createCLIENT() {
        return new CLIENT();
    }

    /**
     * Create an instance of {@link CLIENTCODE }
     * 
     */
    public CLIENTCODE createCLIENTCODE() {
        return new CLIENTCODE();
    }

    /**
     * Create an instance of {@link CLIENTCODEType }
     * 
     */
    public CLIENTCODEType createCLIENTCODEType() {
        return new CLIENTCODEType();
    }

    /**
     * Create an instance of {@link CLIENTMARKETS }
     * 
     */
    public CLIENTMARKETS createCLIENTMARKETS() {
        return new CLIENTMARKETS();
    }

    /**
     * Create an instance of {@link CLIENTMARKETSType }
     * 
     */
    public CLIENTMARKETSType createCLIENTMARKETSType() {
        return new CLIENTMARKETSType();
    }

    /**
     * Create an instance of {@link CLIENTINFO }
     * 
     */
    public CLIENTINFO createCLIENTINFO() {
        return new CLIENTINFO();
    }

    /**
     * Create an instance of {@link CLIENTDU.CLIENTINDIVIDUAL }
     * 
     */
    public CLIENTDU.CLIENTINDIVIDUAL createCLIENTDUCLIENTINDIVIDUAL() {
        return new CLIENTDU.CLIENTINDIVIDUAL();
    }

    /**
     * Create an instance of {@link CLIENTPF.PIF }
     * 
     */
    public CLIENTPF.PIF createCLIENTPFPIF() {
        return new CLIENTPF.PIF();
    }

    /**
     * Create an instance of {@link CLIENTPF.NPFSave }
     * 
     */
    public CLIENTPF.NPFSave createCLIENTPFNPFSave() {
        return new CLIENTPF.NPFSave();
    }

    /**
     * Create an instance of {@link CLIENTPF.NPFReserv }
     * 
     */
    public CLIENTPF.NPFReserv createCLIENTPFNPFReserv() {
        return new CLIENTPF.NPFReserv();
    }

    /**
     * Create an instance of {@link CLIENTPF.NPFUstav }
     * 
     */
    public CLIENTPF.NPFUstav createCLIENTPFNPFUstav() {
        return new CLIENTPF.NPFUstav();
    }

    /**
     * Create an instance of {@link CLIENTPF.PF }
     * 
     */
    public CLIENTPF.PF createCLIENTPFPF() {
        return new CLIENTPF.PF();
    }

    /**
     * Create an instance of {@link CLIENTPF.HomeMilitary }
     * 
     */
    public CLIENTPF.HomeMilitary createCLIENTPFHomeMilitary() {
        return new CLIENTPF.HomeMilitary();
    }

    /**
     * Create an instance of {@link MICEXDOC }
     * 
     */
    public MICEXDOC createMICEXDOC() {
        return new MICEXDOC();
    }

    /**
     * Create an instance of {@link CLIENTS }
     * 
     */
    public CLIENTS createCLIENTS() {
        return new CLIENTS();
    }

    /**
     * Create an instance of {@link INDIVIDUALPERSType.PASSPORTRF }
     * 
     */
    public INDIVIDUALPERSType.PASSPORTRF createINDIVIDUALPERSTypePASSPORTRF() {
        return new INDIVIDUALPERSType.PASSPORTRF();
    }

    /**
     * Create an instance of {@link INDIVIDUALPERSType.PASSPORTUSSR }
     * 
     */
    public INDIVIDUALPERSType.PASSPORTUSSR createINDIVIDUALPERSTypePASSPORTUSSR() {
        return new INDIVIDUALPERSType.PASSPORTUSSR();
    }

    /**
     * Create an instance of {@link INDIVIDUALPERSType.BIRTHCERTIFICATE }
     * 
     */
    public INDIVIDUALPERSType.BIRTHCERTIFICATE createINDIVIDUALPERSTypeBIRTHCERTIFICATE() {
        return new INDIVIDUALPERSType.BIRTHCERTIFICATE();
    }

    /**
     * Create an instance of {@link INDIVIDUALPERSType.OTHERDOC }
     * 
     */
    public INDIVIDUALPERSType.OTHERDOC createINDIVIDUALPERSTypeOTHERDOC() {
        return new INDIVIDUALPERSType.OTHERDOC();
    }

    /**
     * Create an instance of {@link REPRESENTATIVEPERSType.PassportRF }
     * 
     */
    public REPRESENTATIVEPERSType.PassportRF createREPRESENTATIVEPERSTypePassportRF() {
        return new REPRESENTATIVEPERSType.PassportRF();
    }

    /**
     * Create an instance of {@link REPRESENTATIVEPERSType.PassportUSSR }
     * 
     */
    public REPRESENTATIVEPERSType.PassportUSSR createREPRESENTATIVEPERSTypePassportUSSR() {
        return new REPRESENTATIVEPERSType.PassportUSSR();
    }

    /**
     * Create an instance of {@link REPRESENTATIVEPERSType.OtherDoc }
     * 
     */
    public REPRESENTATIVEPERSType.OtherDoc createREPRESENTATIVEPERSTypeOtherDoc() {
        return new REPRESENTATIVEPERSType.OtherDoc();
    }

    /**
     * Create an instance of {@link LEGALPERSDUType.INN }
     * 
     */
    public LEGALPERSDUType.INN createLEGALPERSDUTypeINN() {
        return new LEGALPERSDUType.INN();
    }

    /**
     * Create an instance of {@link LEGALPERSDUType.KIO }
     * 
     */
    public LEGALPERSDUType.KIO createLEGALPERSDUTypeKIO() {
        return new LEGALPERSDUType.KIO();
    }

    /**
     * Create an instance of {@link LEGALPERSType.INN }
     * 
     */
    public LEGALPERSType.INN createLEGALPERSTypeINN() {
        return new LEGALPERSType.INN();
    }

    /**
     * Create an instance of {@link LEGALPERSType.KIO }
     * 
     */
    public LEGALPERSType.KIO createLEGALPERSTypeKIO() {
        return new LEGALPERSType.KIO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CLIENTCODEMAINType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CLIENT_CODE_MAIN")
    public JAXBElement<CLIENTCODEMAINType> createCLIENTCODEMAIN(CLIENTCODEMAINType value) {
        return new JAXBElement<CLIENTCODEMAINType>(_CLIENTCODEMAIN_QNAME, CLIENTCODEMAINType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DOCREQUISITESType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DOC_REQUISITES")
    public JAXBElement<DOCREQUISITESType> createDOCREQUISITES(DOCREQUISITESType value) {
        return new JAXBElement<DOCREQUISITESType>(_DOCREQUISITES_QNAME, DOCREQUISITESType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REPRESENTATIVEPERSType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "REPRESENTATIVE_PERS")
    public JAXBElement<REPRESENTATIVEPERSType> createREPRESENTATIVEPERS(REPRESENTATIVEPERSType value) {
        return new JAXBElement<REPRESENTATIVEPERSType>(_REPRESENTATIVEPERS_QNAME, REPRESENTATIVEPERSType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CLIENTMARKETSMAINType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CLIENT_MARKETS_MAIN")
    public JAXBElement<CLIENTMARKETSMAINType> createCLIENTMARKETSMAIN(CLIENTMARKETSMAINType value) {
        return new JAXBElement<CLIENTMARKETSMAINType>(_CLIENTMARKETSMAIN_QNAME, CLIENTMARKETSMAINType.class, null, value);
    }

}
