//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 05:57:58 PM MSK 
//


package mypackage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Данные для идентификации законного представителя клиента
 * 
 * <p>Java class for REPRESENTATIVE_PERS_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REPRESENTATIVE_PERS_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="PassportRF">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="DocNo" use="required" type="{}PASSPORT_RF_TYPE" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PassportUSSR">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="DocNo" use="required" type="{}PASSPORT_USSR_TYPE" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OtherDoc">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="DocNo" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;maxLength value="20"/>
 *                       &lt;minLength value="1"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REPRESENTATIVE_PERS_Type", propOrder = {
    "passportRF",
    "passportUSSR",
    "otherDoc"
})
public class REPRESENTATIVEPERSType {

    @XmlElement(name = "PassportRF")
    protected REPRESENTATIVEPERSType.PassportRF passportRF;
    @XmlElement(name = "PassportUSSR")
    protected REPRESENTATIVEPERSType.PassportUSSR passportUSSR;
    @XmlElement(name = "OtherDoc")
    protected REPRESENTATIVEPERSType.OtherDoc otherDoc;

    /**
     * Gets the value of the passportRF property.
     * 
     * @return
     *     possible object is
     *     {@link REPRESENTATIVEPERSType.PassportRF }
     *     
     */
    public REPRESENTATIVEPERSType.PassportRF getPassportRF() {
        return passportRF;
    }

    /**
     * Sets the value of the passportRF property.
     * 
     * @param value
     *     allowed object is
     *     {@link REPRESENTATIVEPERSType.PassportRF }
     *     
     */
    public void setPassportRF(REPRESENTATIVEPERSType.PassportRF value) {
        this.passportRF = value;
    }

    /**
     * Gets the value of the passportUSSR property.
     * 
     * @return
     *     possible object is
     *     {@link REPRESENTATIVEPERSType.PassportUSSR }
     *     
     */
    public REPRESENTATIVEPERSType.PassportUSSR getPassportUSSR() {
        return passportUSSR;
    }

    /**
     * Sets the value of the passportUSSR property.
     * 
     * @param value
     *     allowed object is
     *     {@link REPRESENTATIVEPERSType.PassportUSSR }
     *     
     */
    public void setPassportUSSR(REPRESENTATIVEPERSType.PassportUSSR value) {
        this.passportUSSR = value;
    }

    /**
     * Gets the value of the otherDoc property.
     * 
     * @return
     *     possible object is
     *     {@link REPRESENTATIVEPERSType.OtherDoc }
     *     
     */
    public REPRESENTATIVEPERSType.OtherDoc getOtherDoc() {
        return otherDoc;
    }

    /**
     * Sets the value of the otherDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link REPRESENTATIVEPERSType.OtherDoc }
     *     
     */
    public void setOtherDoc(REPRESENTATIVEPERSType.OtherDoc value) {
        this.otherDoc = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="DocNo" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;maxLength value="20"/>
     *             &lt;minLength value="1"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class OtherDoc {

        @XmlAttribute(name = "DocNo", required = true)
        protected String docNo;

        /**
         * Gets the value of the docNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocNo() {
            return docNo;
        }

        /**
         * Sets the value of the docNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocNo(String value) {
            this.docNo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="DocNo" use="required" type="{}PASSPORT_RF_TYPE" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PassportRF {

        @XmlAttribute(name = "DocNo", required = true)
        protected String docNo;

        /**
         * Gets the value of the docNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocNo() {
            return docNo;
        }

        /**
         * Sets the value of the docNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocNo(String value) {
            this.docNo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="DocNo" use="required" type="{}PASSPORT_USSR_TYPE" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PassportUSSR {

        @XmlAttribute(name = "DocNo", required = true)
        protected String docNo;

        /**
         * Gets the value of the docNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocNo() {
            return docNo;
        }

        /**
         * Sets the value of the docNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocNo(String value) {
            this.docNo = value;
        }

    }

}
